# Generated by Django 4.1.5 on 2023-02-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_remove_measurement_sensor_id_sensor_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
