# Generated by Django 4.1 on 2022-09-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                (
                    "image",
                    models.ImageField(height_field=100, upload_to="", width_field=100),
                ),
                ("release_date", models.DateField()),
                ("lte_exists", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
        ),
    ]
