# Generated by Django 4.1 on 2022-09-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0002_alter_phone_lte_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
